# Generated by Django 5.0.2 on 2026-02-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('score_grade', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Fair'), ('D', 'D - Poor'), ('E', 'E - Very Poor')], max_length=2)),
                ('transaction_consistency', models.FloatField()),
                ('average_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('months_of_history', models.IntegerField()),
                ('repayment_history_score', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(max_length=10)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('cashflow_warning', 'Cash Flow Warning'), ('forecast_update', 'Forecast Update'), ('credit_score_change', 'Credit Score Change'), ('reorder_suggestion', 'Reorder Suggestion'), ('payment_due', 'Payment Due')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('suggested_action', models.TextField(blank=True)),
                ('action_data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='businesses.business')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'is_read', 'is_resolved'], name='analytics_a_busines_656e9d_idx'), models.Index(fields=['alert_type', 'severity'], name='analytics_a_alert_t_0b7cc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('sales', 'Sales Forecast'), ('expenses', 'Expenses Forecast'), ('cashflow', 'Cash Flow Forecast')], max_length=10)),
                ('forecast_date', models.DateField()),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence_level', models.FloatField(default=0.95)),
                ('model_used', models.CharField(max_length=50)),
                ('training_data_points', models.IntegerField()),
                ('accuracy_metric', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='businesses.business')),
            ],
            options={
                'ordering': ['-forecast_date', '-created_at'],
                'indexes': [models.Index(fields=['business', 'forecast_type', 'forecast_date'], name='analytics_f_busines_086493_idx')],
            },
        ),
    ]
