# Generated by Django 5.0.2 on 2026-02-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(choices=[('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('agriculture', 'Agriculture'), ('services', 'Services'), ('transport', 'Transport'), ('construction', 'Construction'), ('technology', 'Technology'), ('other', 'Other')], max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('location_description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mpesa_till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('employee_count', models.IntegerField(default=1)),
                ('monthly_revenue_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view_only', 'View Only'), ('add_transactions', 'Add Transactions'), ('full_access', 'Full Access')], default='add_transactions', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_staff', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'is_active'], name='businesses__owner_i_b4b714_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['county', 'sector'], name='businesses__county_48f7da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together={('business', 'user')},
        ),
    ]
