# Generated by Django 6.0.2 on 2026-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
