# Generated by Django 6.0.2 on 2026-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_subscription_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
