# Generated by Django 6.0.2 on 2026-02-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
