# Generated by Django 6.0.2 on 2026-02-25 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_has_seen_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success'), ('debug', 'Debug')], default='info', max_length=10)),
                ('source', models.CharField(choices=[('auth', 'Auth'), ('api', 'API'), ('transactions', 'Transactions'), ('inventory', 'Inventory'), ('system', 'System'), ('admin', 'Admin')], default='system', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
