# Generated by Django 6.0.2 on 2026-02-25 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_systemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systemlog', to=settings.AUTH_USER_MODEL),
        ),
    ]
