# Generated by Django 6.0.2 on 2026-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
