# Generated by Django 6.0.2 on 2026-04-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_customer_supplier'),
        ('inventory', '0002_product_batch_number_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['expiry_date'], name='inventory_p_expiry__8b79d9_idx'),
        ),
    ]
